version: '3.3'

services:

  web:
    build: ./fastapi
    ports:
      - 8004:8004
    command: uvicorn main:app --host 0.0.0.0 --reload --port=8004
    restart: always
    volumes:
      - fastapi-storage:/var/lib/docker/volumes/fastapi-storage/_data
    networks:
      - basenet
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./fastapi
    command: "celery -A main.worker worker -c 2 -l debug -Q celery"
    restart: always
    volumes:
      - fastapi-storage:/var/lib/docker/volumes/fastapi-storage/_data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
    networks:
      - basenet

  redis:
    image: redis:6-alpine
    restart: always
    networks:
      - basenet
 
  dashboard:
    build: ./fastapi
    command:  celery --app=celery --broker=redis://redis:6379/0 flower --host 0.0.0.0 --port=5556
    restart: always
    volumes:
      - fastapi-storage:/var/lib/docker/volumes/fastapi-storage/_data
    ports:
      - 5556:5556
    networks:
      - basenet
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker

networks:
  basenet:

volumes:
  fastapi-storage:
    external: true

