version: '3.3'

services:

  web:
    build: ./fastapi
    ports:
      - 8004:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - fastapi-storage:/var/lib/docker/volumes/fastapi-storage/_data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: ./fastapi
    command: "celery -A main.worker worker -l debug -Q celery"
    volumes:
      - fastapi-storage:/var/lib/docker/volumes/fastapi-storage/_data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine

  dashboard:
    build: ./fastapi
    command: flower --app=worker.app --port=5555 --broker=redis://redis:6379/0
    volumes:
      - fastapi-storage:/var/lib/docker/volumes/fastapi-storage/_data
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker
volumes:
  fastapi-storage:
    external: true