site_name: ZiConnect Backend - AI for education towards employability
site_description: With Unicef Innovation Fund and Giga Project our objective is to leverage the inclusion of young people to better education and more opportunities through internet connectivity.
site_url: https://unicef.jobzi.com

repo_url: https://github.com/Jobzi-Artificial-Intelligence/ziconnect-backend-fastapi
edit_uri: edit/gh-pages/mkdocs/docs

plugins:
  - include-markdown

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky

nav:
  - Home: docs/ABOUT.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - License: LICENSE.md
  - Contributing: docs/CONTRIBUTING.md
  - Project Charter: docs/ROJECT_CHARTER.md
  - FastAPI Setup: docs/FASTAPI_SETUP.md
  - Git Workflow: docs/GIT_WORKFLOW.md
  - Project Modules: README.md