name: FastAPI & Celery Build/Test
 
on:
  push:
    branches:
      - master

  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
               
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiofiles==0.6.0
          pip install celery==4.4.7
          pip install fastapi==0.74.0
          pip install typing-extensions~=3.7.0
          pip install starlette
          pip install setuptools wheel twine

      - name: Install dependencies for CodeCov Test
        run: | 
            pip install codecov
            pip install pytest-cov
            pytest --cov=./ --cov-report=xml
            codecov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: unittests
          verbose: false
      
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        run: tox -e py

      - name: Build package
        run: python -m build
      
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        