name: FastAPI & Celery Build/Test
 
on:
  push:
    branches:
      - master
      - staging

  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r fastapi/requirements.txt

      - name: Create storage volume
        run: docker volume create fastapi-storage

      - name: Build docker-compose
        run: docker-compose build
      
      - name: Up docker-compose
        run: docker-compose up

      - name: Run tests and collect coverage
        run: pytest --cov app

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}


     