name: FastAPI & Celery Build/Test
 
on:
  push:
    branches:
      - master

  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8

      - name: Install dependencies for CodeCov Test
        run: | 
            pip install codecov
            pip install pytest-cov
            pytest --cov=./ --cov-report=xml
            codecov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: unittests
          verbose: false
      
      - run: make setup
      - run: make setup-dev
      - run: conda info
      - run: conda list
      - run: make format
      - run: make lint
        