name: FastAPI & Celery Build/Test & Codecov Report
 
on:
  push:
    branches:
      - master
      - staging

  release:
    types: [created]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: pip3 install -r fastapi/requirements.txt

    - name: Create storage volume
      run: docker volume create fastapi-storage

    - name: Build docker-compose
      run: docker-compose build
      
    - name: Up docker-compose
      run: docker-compose up &
   
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
          token: ${{secrets.CODECOV_TOKEN}}





     