site_name: ZiConnect Backend - AI for education towards employability
site_description: With Unicef Innovation Fund and Giga Project our objective is to leverage the inclusion of young people to better education and more opportunities through internet connectivity.
site_url: https://unicef.jobzi.com

repo_url: https://github.com/Jobzi-Artificial-Intelligence/ziconnect-backend-fastapi
edit_uri: edit/gh-pages/mkdocs/docs

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky

nav:
  - Home: ABOUT.md
  - Contributing: CONTRIBUTING.md
  - Project Charter: PROJECT_CHARTER.md
  - FastAPI Setup: FASTAPI_SETUP.md
  - Git Workflow: GIT_WORKFLOW.md